export const EVENTS = {
  LOAD_SCENE: 'EVENT:SCENE:LOAD',
  SOUND_TOGGLE: 'EVENT:SOUND:TOGGLE',
  APP_UPDATE: 'EVENT:APP:UPDATE',
  CAMERA_FOLLOW: 'EVENT:CAMERA:FOLLOW',
  CAMERA_CLEAR: 'EVENT:CAMERA:CLEAR',
  CAMERA_ZOOM: 'EVENT:CAMERA:ZOOM',
  CAMERA_ZOOM_TO_TARGET: 'EVENT:CAMERA:ZOOM:TARGET',
  CAMERA_RESET_ZOOM: 'EVENT:CAMERA:ZOOM:RESET',
  CAMERA_STOP: 'EVENT:CAMERA:STOP',
} as const;
